# To boot the app run the following:
# docker-compose run start-gpt
version: "3.9"

services:
  start-gpt:
    depends_on:
      - redis
    build: ./
    volumes:
      - "./startgpt:/app"
      - ".env:/app/.env"
    profiles: ["exclude-from-up"]

  redis:
    image: "redis/redis-stack-server:latest"
