# To boot the app run the following:
# docker-compose run start-gpt
# NOTE: Version 3.9 requires at least docker-compose version 1.29.0 !
version: "3.9"

services:
  start-gpt:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./docker-compose.yml:/app/docker-compose.yml:ro
      - ./Dockerfile:/app/Dockerfile:ro
    profiles: ["exclude-from-up"]
