# To boot the app run the following:
# docker-compose run start-gpt
version: '3.9'

services:
  start-gpt:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../
    tty: true
    volumes:
      - ../:/workspace/Start-GPT
