# To boot the app run the following:
# docker-compose run start-gpt
version: '3.9'

services:
  start-gpt:
    depends_on:
      - redis
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../
    tty: true
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ../:/workspace/Start-GPT
  redis:
    image: 'redis/redis-stack-server:latest'
